baseURL = "https://diucagang.fun/"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "Diucagang | Your trustworthy geek culture news site."
theme = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "Categories"
    url= "tags"
    weight= 2
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "GuideGod69"
  authorThumb = "images/author.png"
  authorAddress = "Gamer Avenue, Bangladesh"
  authorPhone = "+54-9999999"
  instaUsername = "guidegod69"
  facebookUsername = "guidegod69"
  twitterUsername = "guidegod69"
  blogTitle = "Latest News"
  blogSubTitle = "View the latest news on your favourite entertainment."
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
